### ISSUE TITLE
Have you finished building the code?

### ISSUE THREAD

**Issue by li-pengcheng** [pomelyu/AnimateGAN#1]
Your work is great, but I found that some functions have not been implemented yet, such as' model.optimize_parameters() '. In fact, I want to get the intermediate result of XGAN network through your code. Can you help me?

**Comment by pomelyu** [comment]
I'm not sure what you talking about. There is the implemented `optimizer_parameters()` in [XGAN.py](https://github.com/pomelyu/AnimateGAN/blob/master/models/XGAN.py). However, I'm not sure whether my implementation is correct or not.

**Comment by liufangcen** [comment]
thank you.
If I want to extract latent features, how do I modify the code?
Can you help me?

**Comment by pomelyu** [comment]
`self.latent_A` and `self.latent_B` may be what you want.

**Comment by liufangcen** [comment]
thanks a lot!

**Comment by liufangcen** [comment]
Can we leave another contact information, such as WeChat? I am studying GAN and hope to have a good communication with the seniors.
